# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170613_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
